<h1 align="center"> Fundamentals of Computer Science - Andrea Leoni 844866 </h1!

### Libraries and Imports

In [236]:
import pandas as pd
import numpy as np
import datetime
pd.set_option('display.max_columns', 50)

dogs = pd.read_csv(r"C:\Users\leonind\OneDrive - Gewiss S.p.A\Documenti\WORK\FCS_Project\adoptions\dogs.csv")
travels = pd.read_csv(r"C:\Users\leonind\OneDrive - Gewiss S.p.A\Documenti\WORK\FCS_Project\adoptions\dogTravel.csv")
states = pd.read_csv(r"C:\Users\leonind\OneDrive - Gewiss S.p.A\Documenti\WORK\FCS_Project\adoptions\NST-EST2021-POP.csv", names=['state', 'population'])

### 1. Extract all dogs with status that is not adoptable

In [206]:
dogs[dogs['status'] != "adoptable"]

,id,org_id,url,type.x,species,breed_primary,breed_secondary,breed_mixed,breed_unknown,color_primary,color_secondary,color_tertiary,age,sex,size,coat,fixed,house_trained,declawed,special_needs,shots_current,env_children,env_dogs,env_cats,name,status,posted,contact_city,contact_state,contact_zip,contact_country,stateQ,accessed,type.y,description,stay_duration,stay_cost
644,41330726,NV173,https://www.petfinder.com/dog/gunther-gunny-41...,Dog,Dog,German Shepherd Dog,NaN,False,False,NaN,NaN,NaN,Young,Male,Large,NaN,False,False,NaN,False,False,NaN,NaN,NaN,"Gunther :Gunny\"",Meet handsome 3 year old Gunt...",2018-04-05T05:18:31+0000,Las Vegas,NV,89146,US,89009,2019-09-20,NaN,Dog,Meet handsome 3 year old Gunther. Gunther came...,108,256.88
5549,38169117,AZ414,https://www.petfinder.com/dog/annabelle-annie-...,Dog,Dog,Boxer,Pit Bull Terrier,True,False,Black,White / Cream,NaN,Adult,Female,Large,Short,True,True,NaN,False,True,NaN,NaN,False,"ANNABELLE \ANNIE\"",""You can fill out an adopti...",2017-05-26T21:43:16+0000,Chandler,AZ,85249,US,AZ,2019-09-20,NaN,Dog,You can fill out an adoption application onlin...,80,130.77
10888,45833989,NY98,https://www.petfinder.com/dog/pepper-courtesy-...,Dog,Dog,Beagle,NaN,False,False,NaN,NaN,NaN,Senior,Male,Medium,Short,True,True,NaN,False,True,True,True,True,"PEPPER \Courtesy listing\"",""This is Pepper. He...",2019-09-01T15:12:06+0000,Albany,NY,12220,US,CT,2019-09-20,NaN,Dog,This is Pepper. He is a 15 year old tri-color ...,86,180.70
11983,45515547,NY98,https://www.petfinder.com/dog/cooper-courtesy-...,Dog,Dog,Mixed Breed,NaN,False,False,NaN,NaN,NaN,Senior,Male,Medium,Short,True,True,NaN,False,True,NaN,NaN,False,"COOPER \courtesy listing\"",""Cooper is 13 years...",2019-08-06T12:15:58+0000,Albany,NY,12220,US,CT,2019-09-20,NaN,Dog,"Cooper is 13 years old, but according to a ver...",105,400.82
12495,45294115,NY98,https://www.petfinder.com/dog/daisy-courtesy-l...,Dog,Dog,Basset Hound,NaN,False,False,Brown / Chocolate,White / Cream,NaN,Senior,Female,Medium,Short,True,True,NaN,False,True,False,False,NaN,"DAISY \courtesy listing\"",""•Basset Hound, fema...",2019-07-18T14:20:58+0000,Albany,NY,12220,US,CT,2019-09-20,NaN,Dog,"â¢Basset Hound, female, â¢10 years \n\nDelig...",57,82.61
12600,45229004,NY1436,https://www.petfinder.com/dog/elmo-momo-452290...,Dog,Dog,American Bulldog,NaN,True,False,NaN,NaN,NaN,Senior,Male,Large,Short,True,True,NaN,False,True,True,True,NaN,"Elmo \MoMo\"",""Hello i&#039;m MoMo or Elmo , 7 ...",2019-07-11T20:34:42+0000,Saugerties,NY,12477,US,CT,2019-09-20,NaN,Dog,"Hello i'm MoMo or Elmo , 7 year old, mixed bre...",73,136.30
12613,45227052,NY1436,https://www.petfinder.com/dog/bianca-pinky-452...,Dog,Dog,Mixed Breed,NaN,False,False,White / Cream,NaN,NaN,Senior,Female,Medium,Short,True,True,NaN,False,True,True,True,NaN,"Bianca \Pinky\"",""Hello I&#039;m Bianca, a fema...",2019-07-11T14:16:38+0000,Saugerties,NY,12477,US,CT,2019-09-20,NaN,Dog,"Hello I'm Bianca, a female, 7 year old mixed b...",107,231.31
17619,45569380,CA1209,https://www.petfinder.com/dog/baby-girl-455693...,Dog,Dog,Maltese,NaN,False,False,White / Cream,NaN,NaN,Senior,Female,Small,Short,True,True,NaN,False,True,True,True,NaN,"\Baby Girl\"",""This 10-year young senior is ver...",2019-08-10T16:00:35+0000,Bristow,VA,20136,US,DC,2019-09-20,NaN,Dog,This 10-year young senior is very sweet and lo...,76,263.63
18611,44694387,MD295,https://www.petfinder.com/dog/king-bert-bertie...,Dog,Dog,Fox Terrier,Chihuahua,True,False,Bicolor,NaN,NaN,Young,Male,Small,Short,True,False,NaN,False,True,False,NaN,False,"King Bert \Bertie\"",""&quot;Bertie&quot; came t...",2019-05-14T21:09:27+0000,Silver Spring,MD,20905,US,DC,2019-09-20,NaN,Dog,"\""Bertie\"" came to us from the shelter. He wa...",61,158.84
19747,36978896,VA127,https://www.petfinder.com/dog/maddie-cutie-pat...,Dog,Dog,Alaskan Malamute,NaN,False,False,Bicolor,NaN,NaN,Adult,Female,Large,NaN,True,True,NaN,False,True,NaN,NaN,False,"Maddie \Cutie Patootie!\"",""Maddie is our littl...",2016-12-15T13:33:43+0000,Gettysburg,PA,17325,US,DC,2019-09-20,NaN,Dog,Maddie is our little Miss Cutie Patootie! She ...,119,431.66
19845,33218331,VA127,https://www.petfinder.com/dog/bucky-are-u-my-h...,Dog,Dog,Alaskan Malamute,Siberian Husky,True,False,Gray / Blue / Silver,NaN,NaN,Adult,Male,Large,Medium,True,True,NaN,False,True,NaN,NaN,False,"Bucky \Are u my hooman?\"",""Born in August 2014...",2015-09-07T12:57:27+0000,Gettysburg,PA,17325,US,DC,2019-09-20,NaN,Dog,"Born in August 2014, Bucky has a great sense o...",98,346.67
22161,42092005,PA738,https://www.petfinder.com/dog/chloe-little-ras...,Dog,Dog,Pit Bull Terrier,Pointer,True,False,Black,White / Cream,NaN,Adult,Female,Medium,Short,True,False,NaN,False,True,True,True,NaN,"CHLOE \LITTLE RASCAL\"",""Meet Chloe our &quot;L...",2018-07-05T00:55:08+0000,Media,PA,19063,US,DE,2019-09-20,NaN,Dog,"Meet Chloe our \""Little Rascal.\",113,279.59
22229,39594038,PA562,https://www.petfinder.com/dog/cozi-h-wilson-lo...,Dog,Dog,Pit Bull Terrier,NaN,True,False,NaN,NaN,NaN,Young,Female,Medium,Short,True,True,NaN,False,True,True,True,NaN,"COZI H WILSON \loves children, cuddlebug\"",""01...",2017-10-07T23:48:20+0000,Feasterville,PA,19053,US,DE,2019-09-20,NaN,Dog,01.04.19\nHi Folks! Iâm Cozi and Iâm so gl...,88,360.84
29283,45895274,IL688,https://www.petfinder.com/dog/gibson-edgar-gib...,Dog,Dog,Labrador Retriever,NaN,True,False,Brown / Chocolate,NaN,NaN,Young,Male,Large,Short,True,True,NaN,False,True,True,True,False,"Gibson Edgar \Gibbs\"",""Gibson Edgar is a 12 mo...",2019-09-07T04:09:12+0000,Paris,IL,61944,US,IL,2019-09-20,NaN,Dog,Gibson Edgar is a 12 month old male Lab mix th...,74,121.56
30471,45964719,IN694,https://www.petfinder.com/dog/puppies-berries-...,Dog,Dog,American Staffordshire Terrier,Border Collie,True,False,Black,White / Cream,NaN,Baby,Female,Medium,Short,False,False,NaN,False,True,True,True,NaN,"PUPPIES \Berries\"",""11 Berry Pups\nIndividual ...",2019-09-13T19:39:28+0000,Mooresville,IN,46158,US,IN,2019-09-20,NaN,Dog,11 Berry Pups\nIndividual pics will be done. ...,127,429.87
31581,44538917,OH907,https://www.petfinder.com/dog/leila-courtesy-p...,Dog,Dog,Australian Shepherd,Husky,True,False,"Tricolor (Brown, Black, & White)",NaN,NaN,Adult,Female,Medium,Short,True,True,NaN,False,True,NaN,NaN,NaN,"Leila \COURTESY POST\"",""THIS IS A COURTESY POS...",2019-04-25T01:56:52+0000,Ross,OH,45061,US,IN,2019-09-20,NaN,Dog,THIS IS A COURTESY POST (this means that any a...,92,188.49
31888,41430442,OH907,https://www.petfinder.com/dog/eden-in-training...,Dog,Dog,Hound,NaN,True,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Adult,Female,Medium,Short,True,False,NaN,False,True,NaN,False,NaN,"Eden \In Training\"",""Eden is estimated 3 years...",2018-04-18T13:45:46+0000,Ross,OH,45061,US,IN,2019-09-20,NaN,Dog,Eden is estimated 3 years old and weighs 40 lb...,97,238.60
33000,45907639,IN714,https://www.petfinder.com/dog/coach-chris-mack...,Dog,Dog,Chihuahua,Beagle,True,False,Yellow / Tan / Blond / Fawn,NaN,NaN,Adult,Male,Small,Short,True,True,NaN,False,True,True,True,NaN,"Coach Chris \Mack\"",""Mack is a 2 year old, 13 ...",2019-09-08T18:21:21+0000,Jeffersonville,IN,47131,US,KY,2019-09-20,NaN,Dog,"Mack is a 2 year old, 13 pound furry chihuahua...",101,478.36
33527,45362806,OH852,https://www.petfinder.com/dog/liberty-libby-45...,Dog,Dog,Pomeranian,NaN,False,False,NaN,NaN,NaN,Adult,Female,Small,Long,True,False,NaN,False,True,False,True,True,"Liberty \Libby\"",""Liberty came to us on the 3r...",2019-07-25T19:53:21+0000,Cincinnati,OH,45249,US,KY,2019-09-20,NaN,Dog,Liberty came to us on the 3rd of July - she ha...,65,185.05
34188,32590894,IN595,https://www.petfinder.com/dog/samson-sam-32590...,Dog,Dog,Mastiff,Labrador Retriever,True,False,Black,NaN,NaN,Adult,Male,Extra Large,NaN,False,False,NaN,False,False,NaN,NaN,NaN,"Samson \Sam\"",""DUE TO PROBLEMS WITH THE CURREN...",2015-06-29T23:58:09+0000,Paoli,IN,47454,US,KY,2019-09-20,NaN,Dog,DUE TO PROBLEMS WITH THE CURRENT PETFINDER UPD...,116,413.96
35065,31426754,LA256,https://www.petfinder.com/dog/sully-sullivan-3...,Dog,Dog,Pit Bull Terrier,NaN,False,False,Black,NaN,NaN,Young,Male,Medium,Short,True,True,NaN,False,True,NaN,NaN,NaN,"Sully \Sullivan\"",""Hi my name is Sully! I get ...",2015-02-07T13:06:43+0000,lake charles,LA,70601,US,LA,2019-09-20,NaN,Dog,Hi my name is Sully! I get along with most dog...,122,204.63
44830,46037827,NM133,https://www.petfinder.com/dog/periwinkle-wink-...,Dog,Dog,Australian Shepherd,Spaniel,True,False,Brown / Chocolate,White / Cream,NaN,Adult,Female,Medium,Medium,True,True,NaN,False,True,True,True,NaN,"PERIWINKLE \WINK\"",""We take the time to post p...",2019-09-20T01:50:51+0000,Albuquerque,NM,87108,US,NM,2019-09-20,NaN,Dog,We take the time to post pertinent information...,85,296.75
53168,44044071,TN669,https://www.petfinder.com/dog/raymond-reddingt...,Dog,Dog,American Staffordshire Terrier,NaN,True,False,Red / Chestnut / Orange,NaN,NaN,Adult,Male,Medium,Medium,True,False,NaN,False,False,True,NaN,False,"Raymond \Reddington\"",""Red is a 4-5 yr old St...",2019-02-18T12:02:48+0000,Cookeville,TN,38506,US,TN,2019-09-20,NaN,Dog,Red is a 4-5 yr old Staffey mix that is a wig...,88,230.12
53539,27521132,TN577,https://www.petfinder.com/dog/norma-rose-rosie...,Dog,Dog,Yellow Labrador Retriever,American Staffordshire Terrier,True,False,Yellow / Tan / Blond / Fawn,NaN,NaN,Adult,Female,Large,Short,True,True,NaN,False,True,True,False,False,"Norma Rose \ROSIE\"",""Robyn&#039;s Nest Animal ...",2013-10-10T13:57:39+0000,Nashville,TN,37189,US,TN,2019-09-20,NaN,Dog,Robyn's Nest Animal Rescue & SanctuaryNashvill...,93,300.50
55434,38473806,VA486,https://www.petfinder.com/dog/markey-moose-384...,Dog,Dog,Hound,NaN,False,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Adult,Male,Large,Short,False,True,NaN,False,True,True,True,NaN,"Markey \Moose\"",""Markey &quot;Moose&quot; firs...",2017-06-16T18:44:33+0000,Rustburg,VA,24588,US,VA,2019-09-20,NaN,Dog,"Markey \""Moose\"" first came to us after being ...",78,71.15
55467,34101432,VA628,https://www.petfinder.com/dog/george-boy-georg...,Dog,Dog,Labrador Retriever,NaN,True,False,Yellow / Tan / Blond / Fawn,White / Cream,NaN,Young,Male,Medium,Short,True,False,NaN,False,True,NaN,NaN,NaN,"George \Boy George\"",""Contact dojennings@Comca...",2015-12-25T12:28:30+0000,Midlothian,VA,23112,US,VA,2019-09-20,NaN,Dog,Contact dojennings@Comcast.net or Debbie Jenni...,115,320.23
55915,45958435,WA581,https://www.petfinder.com/dog/skipper-45958435...,Dog,Dog,Yorkshire Terrier,Terrier,True,False,"Tricolor (Brown, Black, & White)",White / Cream,Yellow / Tan / Blond / Fawn,Young,Male,Small,Medium,True,False,NaN,False,True,NaN,True,True,"\Skipper\"",""For a quicker response please subm...",2019-09-13T06:08:17+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,For a quicker response please submit a online ...,102,338.18
55975,45927580,WA581,https://www.petfinder.com/dog/bella-45927580/w...,Dog,Dog,Chihuahua,NaN,False,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Adult,Female,Small,Short,True,True,NaN,True,True,False,True,NaN,"\Bella\"",""Meet &quot;Bella&quot; She is a ador...",2019-09-10T16:43:35+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet \""Bella\"" She is a adorable and 7 pounds ...",102,407.51
56013,45916348,WA581,https://www.petfinder.com/dog/cody-45916348/wa...,Dog,Dog,Golden Retriever,Terrier,True,False,Bicolor,"Tricolor (Brown, Black, & White)",NaN,Adult,Male,Medium,Short,True,True,NaN,False,True,True,True,NaN,"\Cody\"",""*Please apply online at www.6dogrees....",2019-09-09T17:05:17+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,*Please apply online at www.6dogrees.com to ge...,92,164.55
56248,45733027,WA581,https://www.petfinder.com/dog/gracie-45733027/...,Dog,Dog,Papillon,Cavalier King Charles Spaniel,True,False,Golden,Red / Chestnut / Orange,NaN,Adult,Female,Small,Medium,True,True,NaN,False,True,NaN,True,NaN,"\Gracie\"",""Meet &quot;Gracie&quot; a very beau...",2019-08-24T16:32:31+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet \""Gracie\"" a very beautiful 11 pound,fema...",82,168.54
56464,45413997,WA581,https://www.petfinder.com/dog/jameson-45413997...,Dog,Dog,Rat Terrier,Chihuahua,True,False,"Tricolor (Brown, Black, & White)",White / Cream,NaN,Young,Male,Small,NaN,True,False,NaN,False,True,False,True,True,"\Jameson\"",""Meet &quot;Jameson&quot; He is a v...",2019-07-31T16:21:07+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet \""Jameson\"" He is a very handsome 9 pound...",108,297.27
56473,45406516,WA581,https://www.petfinder.com/dog/canelo-45406516/...,Dog,Dog,Chihuahua,Terrier,True,False,Bicolor,Golden,NaN,Adult,Male,Small,Short,True,False,NaN,False,True,False,True,NaN,"\Canelo\"",""Meet Canelo a adorable small, tan...",2019-07-29T21:50:16+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet Canelo a adorable small, tan very sweet...",94,312.10
56541,45264615,WA581,https://www.petfinder.com/dog/noni-45264615/wa...,Dog,Dog,Chihuahua,Terrier,True,False,Black,White / Cream,NaN,Adult,Female,Small,NaN,True,True,NaN,False,True,False,True,False,"\Noni\"",""Meet &quot;Noni&quot; She is a Black ...",2019-07-15T16:57:05+0000,Seattle,WA,98106,US,WA,2019-09-20,NaN,Dog,"Meet \""Noni\"" She is a Black and white smooth ...",77,290.16

### 2. For each (primary) breed, determine the number of dogs

In [207]:
pd.DataFrame(dogs['breed_primary'].value_counts())

                                     breed_primary
Pit Bull Terrier                              7890
Labrador Retriever                            7198
Chihuahua                                     3766
Mixed Breed                                   3242
Terrier                                       2641
Hound                                         2282
German Shepherd Dog                           2122
Boxer                                         2050
Shepherd                                      1972
American Staffordshire Terrier                1862
Beagle                                        1539
American Bulldog                              1134
Australian Cattle Dog / Blue Heeler            973
Dachshund                                      853
Border Collie                                  817
Australian Shepherd                            696
Jack Russell Terrier                           637
Husky                                          567
Black Labrador Retriever                       545
Retriever                                      538
Rottweiler                                     533
Catahoula Leopard Dog                          488
Great Pyrenees                                 481
Cattle Dog                                     444
Siberian Husky                                 439
...                                            ...
Coton de Tulear                                  2
Curly-Coated Retriever                           2
Gordon Setter                                    2
Entlebucher                                      2
German Spitz                                     2
Norwegian Buhund                                 2
Belgian Shepherd / Tervuren                      2
Otterhound                                       2
Bouvier des Flandres                             1
Kai Dog                                          1
Skye Terrier                                     1
Chinese Foo Dog                                  1
Kuvasz                                           1
Bolognese                                        1
Fila Brasileiro                                  1
Spinone Italiano                                 1
Briard                                           1
Leonberger                                       1
Field Spaniel                                    1
Chinook                                          1
Wirehaired Pointing Griffon                      1
Boykin Spaniel                                   1
Old English Sheepdog                             1
Belgian Shepherd / Laekenois                     1
Tosa Inu                                         1

[216 rows x 1 columns]

### 3. For each (primary) breed, determine the ratio between the number of dogs of Mixed Breed and those not of Mixed Breed. Hint: look at the secondary_breed

In [208]:
# Groups the dogs by primary breed
primaryBreedGroup = dogs.groupby(['breed_primary'])

# Computes the percentage ratio of mexid breed per primary breed
mixedDogsRatioTable = pd.DataFrame(primaryBreedGroup['breed_mixed'].value_counts(normalize=True))
mixedDogsRatioTable.columns = ['ratio']
mixedDogsRatioTable

                                                     ratio
breed_primary                        breed_mixed
Affenpinscher                        False        0.705882
                                     True         0.294118
Afghan Hound                         True         1.000000
Airedale Terrier                     True         0.894737
                                     False        0.105263
Akbash                               True         0.666667
                                     False        0.333333
Akita                                False        0.541436
                                     True         0.458564
Alaskan Malamute                     False        0.722222
                                     True         0.277778
American Bulldog                     True         0.776896
                                     False        0.223104
American Eskimo Dog                  False        0.558140
                                     True         0.441860
American Foxhound                    True         0.705882
                                     False        0.294118
American Hairless Terrier            False        0.500000
                                     True         0.500000
American Staffordshire Terrier       True         0.701933
                                     False        0.298067
Anatolian Shepherd                   True         0.906780
                                     False        0.093220
Australian Cattle Dog / Blue Heeler  True         0.769784
                                     False        0.230216
...                                                    ...
Vizsla                               True         0.966667
                                     False        0.033333
Weimaraner                           True         0.603175
                                     False        0.396825
West Highland White Terrier / Westie True         0.789474
                                     False        0.210526
Wheaten Terrier                      True         0.736842
                                     False        0.263158
Whippet                              True         0.927711
                                     False        0.072289
White German Shepherd                True         0.764706
                                     False        0.235294
Wire Fox Terrier                     True         0.866667
                                     False        0.133333
Wirehaired Dachshund                 True         0.750000
                                     False        0.250000
Wirehaired Pointing Griffon          True         1.000000
Wirehaired Terrier                   True         0.750000
                                     False        0.250000
Xoloitzcuintli / Mexican Hairless    False        0.545455
                                     True         0.454545
Yellow Labrador Retriever            True         0.772152
                                     False        0.227848
Yorkshire Terrier                    True         0.563889
                                     False        0.436111

[394 rows x 1 columns]

### 4. For each (primary) breed, determine the earliest and the latest posted timestamp

In [209]:
# Finds the last and min 'posted' for every primary breed
maxPosted = pd.Series(primaryBreedGroup['posted'].last())
minPosted = pd.Series(primaryBreedGroup['posted'].min())

# Unites the two series in one dataframe
postedTimestampTable = pd.concat([minPosted, maxPosted], axis=1)
postedTimestampTable.columns = ['earliest posted', 'latest posted']
postedTimestampTable

,earliest posted,latest posted
breed_primary,,
Affenpinscher,2012-03-08T10:27:33+0000,2019-09-11T10:02:07+0000
Afghan Hound,2017-06-29T23:28:51+0000,2017-10-24T01:47:44+0000
Airedale Terrier,2014-06-13T12:59:36+0000,2019-09-08T14:16:36+0000
Akbash,2019-07-21T00:35:59+0000,2019-07-21T00:35:59+0000
Akita,2012-03-03T09:31:08+0000,2019-06-25T17:25:06+0000
Alaskan Malamute,2015-02-24T13:18:06+0000,2019-08-31T10:09:31+0000
American Bulldog,2009-03-11T00:00:00+0000,2019-01-08T17:01:16+0000
American Eskimo Dog,2017-04-27T18:39:24+0000,2019-07-28T14:37:55+0000
American Foxhound,2019-02-06T03:06:20+0000,2019-02-10T19:46:32+0000
American Hairless Terrier,2013-07-03T10:05:41+0000,2013-07-03T10:05:41+0000
American Staffordshire Terrier,2007-10-07T00:00:00+0000,2019-07-27T00:57:22+0000
Anatolian Shepherd,2014-03-12T08:36:07+0000,2019-07-19T02:09:29+0000
Australian Cattle Dog / Blue Heeler,2010-11-13T00:00:00+0000,2019-07-04T18:18:41+0000
Australian Kelpie,2011-07-31T07:32:36+0000,2018-03-03T07:38:26+0000
Australian Shepherd,2008-11-06T00:00:00+0000,2019-04-13T16:20:24+0000
Australian Terrier,2017-02-17T16:34:02+0000,2019-09-13T20:08:24+0000
Basenji,2009-10-15T00:00:00+0000,2019-09-10T21:49:34+0000
Basset Hound,2011-11-11T13:27:32+0000,2019-07-14T02:16:47+0000
Beagle,2003-05-18T00:00:00+0000,2019-09-09T23:14:32+0000
Bearded Collie,2018-06-08T06:57:28+0000,2019-08-27T01:20:34+0000
Beauceron,2019-09-05T18:52:36+0000,2019-09-15T22:15:19+0000
Belgian Shepherd / Laekenois,2019-09-03T22:01:52+0000,2019-09-03T22:01:52+0000
Belgian Shepherd / Malinois,2014-04-05T20:03:13+0000,2019-07-18T13:05:07+0000
Belgian Shepherd / Sheepdog,2019-07-19T14:20:19+0000,2019-07-25T03:25:10+0000
Belgian Shepherd / Tervuren,2017-03-31T21:34:30+0000,2019-09-02T15:58:23+0000
...,...,...
Spitz,2011-03-28T20:15:41+0000,2019-06-29T18:59:23+0000
Staffordshire Bull Terrier,2008-03-20T00:00:00+0000,2015-06-09T14:22:25+0000
Standard Poodle,2018-07-17T23:01:48+0000,2018-07-17T23:01:48+0000
Standard Schnauzer,2018-10-08T02:38:55+0000,2019-08-27T20:23:24+0000
Terrier,2006-10-17T00:00:00+0000,2019-07-04T18:18:41+0000
Thai Ridgeback,2019-04-10T16:42:47+0000,2019-05-11T12:51:57+0000
Tibetan Mastiff,2018-10-06T22:09:26+0000,2019-07-15T21:40:09+0000
Tibetan Spaniel,2012-10-04T16:24:58+0000,2019-08-29T13:04:19+0000
Tibetan Terrier,2019-08-18T17:03:34+0000,2019-08-31T22:15:41+0000
Tosa Inu,2019-09-04T00:48:24+0000,2019-09-04T00:48:24+0000
Toy Fox Terrier,2013-12-12T20:05:04+0000,2019-05-26T11:06:58+0000
Treeing Walker Coonhound,2009-03-03T00:00:00+0000,2018-02-11T14:00:29+0000
Vizsla,2016-06-13T22:14:52+0000,2018-06-08T20:14:17+0000
Weimaraner,2012-05-24T12:32:25+0000,2019-09-08T10:39:31+0000
West Highland White Terrier / Westie,2008-03-31T00:00:00+0000,2019-08-31T11:45:42+0000
Wheaten Terrier,2018-06-25T19:37:22+0000,2019-09-15T16:34:01+0000
Whippet,2017-01-27T17:25:06+0000,2019-08-31T10:09:32+0000
White German Shepherd,2016-09-03T00:21:06+0000,2017-05-20T16:21:58+0000
Wire Fox Terrier,2013-12-11T17:08:03+0000,2017-09-19T21:05:50+0000
Wirehaired Dachshund,2019-04-08T23:12:04+0000,2019-09-03T01:40:21+0000
Wirehaired Pointing Griffon,2016-06-29T20:03:55+0000,2016-06-29T20:03:55+0000
Wirehaired Terrier,2012-11-27T14:07:54+0000,2019-06-15T19:20:08+0000
Xoloitzcuintli / Mexican Hairless,2007-02-01T00:00:00+0000,2007-02-01T00:00:00+0000
Yellow Labrador Retriever,2010-05-31T00:00:00+0000,2014-03-03T10:19:48+0000
Yorkshire Terrier,2012-02-04T17:14:52+0000,2019-09-12T00:17:55+0000

### 5. For each state, compute the sex imbalance, that is the difference between male and female dogs. In which state this imbalance is largest?

In [210]:
# Conts the number of female and male for every state
stateSexGroup = dogs.groupby(['contact_state'])
sexDogsState = pd.DataFrame(stateSexGroup['sex'].value_counts())
sexDogsState.columns = ['count']

# Pivots the table to have 'female' and 'male' as headers
sexDogsState = pd.pivot_table(sexDogsState, values='count', index=['contact_state'], columns=['sex'])
# Computs the difference between male and female into the 'Result' column
sexDogsState['Result'] = abs(sexDogsState['Male'] - sexDogsState['Female'])
# Shots where the difference is the highest
pd.DataFrame(sexDogsState.loc[sexDogsState['Result'].idxmax()]).columns

Index(['OH'], dtype='object')

### 6. For each pair (age, size), determine the average duration of the stay and the average cost of stay.

In [276]:
# Calculates the average stay duration and cost for every dog 'age' and 'size' combination
ageSizeGroup = dogs.groupby(['age', 'size'])
meanStay = ageSizeGroup['stay_duration'].mean()
meanCost = ageSizeGroup['stay_cost'].mean()

# Combines the results in one dataframe
pd.concat([meanStay, meanCost], axis=1)

                    stay_duration   stay_cost
age    size
Adult  Extra Large      89.015414  232.591561
       Large            89.531943  238.661141
       Medium           89.421036  238.258977
       Small            89.407479  238.974838
Baby   Extra Large      87.032967  237.180879
       Large            89.701564  238.698827
       Medium           89.577668  237.108131
       Small            89.958291  239.083810
Senior Extra Large      88.861111  235.232361
       Large            88.984298  237.507364
       Medium           89.810052  238.514615
       Small            89.073626  238.282286
Young  Extra Large      90.586345  245.835582
       Large            90.104206  238.149506
       Medium           89.515123  239.304603
       Small            89.814275  241.540069

### 7. Find the dogs involved in at least 3 travels. Also list the breed of those dogs.

In [212]:
# Merges the dataframes 'dogs' and 'travels'
mergedDogsTravels = pd.merge(dogs, travels, on='id')
# Counts the travels for eache dog
countDogsTravels = pd.DataFrame(mergedDogsTravels['id'].value_counts())
# Keeps the merged dataframe of 'dogs' and 'travels' with only the rows of dogs with >= 3 travels
countDogsTravels = countDogsTravels.loc[countDogsTravels['id'] >= 3]
dogsWith3Travels = mergedDogsTravels.loc[mergedDogsTravels['id'].isin(countDogsTravels.index)]

# Extracts the 'id' and 'breed_primary' from the last result and then counts again the number of travels per dog
dogsWith3Travels = dogsWith3Travels[['id', 'breed_primary']]
dogsWith3Travels = pd.DataFrame(dogsWith3Travels.groupby(['id', 'breed_primary']).value_counts())
dogsWith3Travels.columns = ['number of travels']
dogsWith3Travels

                                              number of travels
id       breed_primary
16657005 Pit Bull Terrier                                     4
20905974 Chow Chow                                            5
24894870 Hound                                                4
24894894 Hound                                                4
33218331 Alaskan Malamute                                     7
36978896 Alaskan Malamute                                     7
37108842 Pit Bull Terrier                                     3
37253070 Labrador Retriever                                   4
37848260 Labrador Retriever                                   4
38050885 Pit Bull Terrier                                     3
38495992 Pit Bull Terrier                                     3
38664932 Pit Bull Terrier                                     3
39608594 Pointer                                              3
40036107 Pit Bull Terrier                                     3
40103682 Rat Terrier                                          3
41144335 Chihuahua                                            3
41359772 German Shepherd Dog                                  4
42445043 Dutch Shepherd                                       5
42525486 Cairn Terrier                                        3
42778494 Jack Russell Terrier                                 3
42825396 Parson Russell Terrier                               3
42835971 Pit Bull Terrier                                     3
43082511 Saluki                                               3
43379087 Labrador Retriever                                   3
43401994 Labrador Retriever                                   3
...                                                         ...
46038131 Labrador Retriever                                   3
46038191 Labrador Retriever                                   3
46038194 Yorkshire Terrier                                    3
46038201 Labrador Retriever                                   3
46038273 Labrador Retriever                                   3
46038279 Labrador Retriever                                   3
46038304 Labrador Retriever                                   3
46038340 Labrador Retriever                                   3
46038360 Labrador Retriever                                   3
46038373 Labrador Retriever                                   3
46038557 Retriever                                            3
46039420 Border Collie                                        4
46039516 Doberman Pinscher                                    3
46039522 Australian Cattle Dog / Blue Heeler                  3
46039523 German Shepherd Dog                                  3
46041165 Shepherd                                             4
46041402 Labrador Retriever                                   4
46041584 Labrador Retriever                                   4
46042334 Labrador Retriever                                   3
46042372 Labrador Retriever                                   3
46042569 Labrador Retriever                                   3
46042587 Labrador Retriever                                   3
46042618 Labrador Retriever                                   3
46043099 Labrador Retriever                                   3
46043149 Labrador Retriever                                   3

[563 rows x 1 columns]

### 8. Fix the travels table so that the correct state is computed from the manual and the found fields. If manual is not missing, then it overrides what is stored in found.

In [213]:
# Changes the 'found' column value to the value of the column 'manual' if the column 'manual' is not null
travels['found'] = np.where(travels['manual'].isnull() == False, travels['manual'], travels['found'])
travels

,index,id,contact_city,contact_state,description,found,manual,remove,still_there
0,0,44520267,Anoka,MN,Boris is a handsome mini schnauzer who made hi...,Arkansas,NaN,NaN,NaN
1,1,44698509,Groveland,FL,Duke is an almost 2 year old Potcake from Abac...,Bahamas,Bahamas,NaN,NaN
2,2,45983838,Adamstown,MD,Zac Woof-ron is a heartthrob movie star lookin...,Maryland,Maryland,NaN,NaN
3,3,44475904,Saint Cloud,MN,~~Came in to the shelter as a transfer from an...,Adaptil,NaN,True,NaN
4,4,43877389,Pueblo,CO,Palang is such a sweetheart. She loves her peo...,Afghanistan,NaN,NaN,NaN
5,5,43082511,Manchester,CT,Brooke has an unusual past. She was rescued f...,Afghanistan,NaN,NaN,NaN
6,6,45287347,Wooster,OH,"Tate is an adorable 2 year old, 22 pound Cocka...",Ohio,Ohio,NaN,NaN
7,7,45287347,Wooster,OH,"Tate is an adorable 2 year old, 22 pound Cocka...",Ohio,Ohio,NaN,NaN
8,8,45987719,Locust Fork,AL,Meet Trixie... she is a female 2yr. Old Chihua...,Alabama,NaN,NaN,NaN
9,9,45943086,Locust Fork,AL,"Meet Reba, a 2-year-old Dachshund with a sleek...",Alabama,NaN,NaN,NaN
10,10,45942459,Locust Fork,AL,What a sweet boy Moric is! A 1-year-old mix of...,Alabama,NaN,NaN,NaN
11,11,45942229,Locust Fork,AL,Bert is a 2-year old Chihuahua mix who weighs ...,Alabama,NaN,NaN,NaN
12,12,45941983,Locust Fork,AL,"Gypsy Girl is a 4-year-old, 15-pound Chihuahua...",Alabama,NaN,NaN,NaN
13,13,45898359,Locust Fork,AL,This boy is full of personality! He thinks he ...,Alabama,NaN,NaN,NaN
14,14,45886372,Locust Fork,AL,"Meet Pepper... she is the sweetest baby, so lo...",Alabama,NaN,NaN,NaN
15,15,45886371,Locust Fork,AL,Meet Roxie ... who doesn't love a Hound? They ...,Alabama,NaN,NaN,NaN
16,16,45864590,Locust Fork,AL,"Meet Aiden... he is a great boy, he is about 5...",Alabama,NaN,NaN,NaN
17,17,45863153,Locust Fork,AL,Meet Pippin .... she is adorable. She is good ...,Alabama,NaN,NaN,NaN
18,18,45862971,Locust Fork,AL,Meet Lamb Chop.... he is an adorable guy. He's...,Alabama,NaN,NaN,NaN
19,19,45852535,Locust Fork,AL,Ponce...he is a little on the shy side but war...,Alabama,NaN,NaN,NaN
20,20,45850607,Locust Fork,AL,Meet Misha... this is a sweetie. She has puppy...,Alabama,NaN,NaN,NaN
21,21,45800965,Locust Fork,AL,ZELDA FEMALE AGE 6 MONTHS GRIFFON SMOOTH COAT ...,Alabama,NaN,NaN,NaN
22,22,45800836,Locust Fork,AL,LOKI MALE CHIHUAHUA AGE 8 MONTHS WEIGHT 9 POUN...,Alabama,NaN,NaN,NaN
23,23,45795675,Locust Fork,AL,DaiseyFEMALECHIHUAHUA AGE 16 WEEKSWEIGHT 8.4 P...,Alabama,NaN,NaN,NaN
24,24,45795582,Locust Fork,AL,DAISEY and MAXINE FEMALE CHIHUAHUA AGE 16 WEEK...,Alabama,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6169,6169,45923894,Ellicott City,MD,These puppies were rescued from a WV high kill...,West Virginia,West Virginia,NaN,NaN
6170,6170,45852132,Newville,PA,"Tyr, Heimdall and Baldur are baby puppies, the...",West Virginia,West Virginia,NaN,NaN
6171,6171,45852075,Newville,PA,"Tyr, Heimdall and Baldur are baby puppies, the...",West Virginia,West Virginia,NaN,NaN
6172,6172,45851946,Newville,PA,"Chevelle and Benz are baby puppies, the most p...",West Virginia,West Virginia,NaN,NaN
6173,6173,45851313,Newville,PA,"Chevelle and Benz are baby puppies, the most p...",West Virginia,West Virginia,NaN,NaN
6174,6174,44293601,Snellville,GA,Micki is a beautiful 7 year old female who com...,West Virginia,West Virginia,NaN,NaN
6175,6175,44895276,Marlinton,WV,He is in need of rescue or adoption from the P...,West Virginia,West Virginia,NaN,NaN
6176,6176,38779404,Nazareth,PA,"A Reason To Believe Animal Rescue, Inc.\nhttp:...",West Virginia,West Virginia,NaN,True
6177,6177,38779405,Nazareth,PA,"A Reason To Believe Animal Rescue, Inc.\nhttp:...",West Virginia,West Virginia,NaN,True
6178,6178,45919924,Fairmont,WV,Please contact Pet (information@pethelpersinc....,West Virginia,West Virginia,NaN,True
6179,6179,45903674,Fairmont,WV,Please contact Pet (information@pethelpersinc....,WV,NaN,True,NaN
6180,6180,45524238,Fairmont,WV,Please contact Pet (information@pethelpersinc....,West Virginia,West Virginia,NaN,True
6181,6181,45408933,Fairmont,WV,Please contact Pet (information@pethelpersinc....,West Virginia,West Virginia,NaN,True
6182,6182,45188051,Fairmont,WV,Please contact Pet (information@pethelpersinc....,West Virginia,West Virginia,NaN,True
6183,6183,45017651,Fairmont,WV,Please contact Pet (information@pethelpersinc....,West Virginia,West Virginia,NaN,True
6184,6184,44659739,Fairmont,WV,Please contact Pet (information@pethelpersinc....,West Virginia,West Virginia,NaN,True
6185,6185,44289536,Fairmont,WV,Please contact Pet (information@pethelpersinc....,West Virginia,West Virginia,NaN,True
6186,6186,42628397,Fairmont,WV,Please contact Pet (information@pethelpersinc....,WV,NaN,True,NaN
6187,6187,42117845,Fairmont,WV,This is Dachshund Chihuahua Blue who weighs 7l...,West Virginia,West Virginia,NaN,True
6188,6188,41298157,Fairmont,WV,Please contact Pet (information@pethelpersinc....,WV,NaN,True,NaN
6189,6189,40492179,Fairmont,WV,Please contact Pet (information@pethelpersinc....,WV,NaN,True,NaN
6190,6190,45799729,Eagle Mountain,UT,Shiny is an approximately 4-6-year-old spayed ...,Wyoming,NaN,NaN,NaN
6191,6191,34276515,Newnan,GA,Yanni is a Male Great Pyrenees that we rescue...,Yazmin,NaN,True,NaN
6192,6192,44519341,Dayton,OH,Callie is a 14 year old Chihuahua whose owner ...,Ohio,Ohio,NaN,NaN
6193,6193,36659999,New York,NY,This guy loves to be outside so a person w/ a ...,Zazu,NaN,True,NaN

### 9. For each state, compute the ratio between the number of travels and the population.

In [214]:
mergedTravelsStates = pd.merge(states, travels, left_on='state', right_on='found', how = "left")

mergedTravelsStates['counting'] = np.where(mergedTravelsStates['found'].isnull() == False, 1, 0)

countTravelsStates = pd.DataFrame(mergedTravelsStates.groupby(['state', 'population'])['counting'].sum())
countTravelsStates.columns = ['number_of_travels'] 
countTravelsStates['ratio'] = countTravelsStates['number_of_travels']*2
countTravelsStates

                                 number_of_travels  ratio
state                population
Alabama              5.024.279                 338    676
Alaska               733.391                     0      0
Arizona              7.151.502                  33     66
Arkansas             3.011.524                  61    122
California           39.538.223                279    558
Colorado             5.773.714                  11     22
Connecticut          3.605.944                  16     32
Delaware             989.948                    27     54
District of Columbia 689.545                     0      0
Florida              21.538.187                163    326
Georgia              10.711.908                235    470
Hawaii               1.455.271                   4      8
Idaho                1.839.106                   4      8
Illinois             12.812.508                 33     66
Indiana              6.785.528                  17     34
Iowa                 3.190.369                   7     14
Kansas               2.937.880                   3      6
Kentucky             4.505.836                  99    198
Louisiana            4.657.757                  69    138
Maine                1.362.359                  13     26
Maryland             6.177.224                 140    280
Massachusetts        7.029.917                  13     26
Michigan             10.077.331                 29     58
Minnesota            5.706.494                  80    160
Mississippi          2.961.279                  62    124
...                                            ...    ...
Montana              1.084.225                   0      0
Nebraska             1.961.504                   4      8
Nevada               3.104.614                   3      6
New Hampshire        1.377.529                   2      4
New Jersey           9.288.994                  44     88
New Mexico           2.117.522                  84    168
New York             20.201.249                 63    126
North Carolina       10.439.388                292    584
North Dakota         779.094                     2      4
Ohio                 11.799.448                 72    144
Oklahoma             3.959.353                  32     64
Oregon               4.237.256                   2      4
Pennsylvania         13.002.700                 50    100
Rhode Island         1.097.379                   4      8
South Carolina       5.118.425                 221    442
South Dakota         886.667                     2      4
Tennessee            6.910.840                 144    288
Texas                29.145.505                959   1918
Utah                 3.271.616                  10     20
Vermont              643.077                     1      2
Virginia             8.631.393                 306    612
Washington           7.705.281                  11     22
West Virginia        1.793.716                 117    234
Wisconsin            5.893.718                   7     14
Wyoming              576.851                     1      2

[51 rows x 2 columns]

### 10. For each dog, compute the number of days from the posted day to the day of last access.

In [289]:
dogs["accessed"] = pd.to_datetime(dogs["accessed"], utc=True)

dogs['numberOfDays'] = (dogs["accessed"] - dogs['posted']).dt.days+1
dogs[['id', 'numberOfDays']]

             id  numberOfDays
0      46042150           0.0
1      46042002           0.0
2      46040898           0.0
3      46039877           0.0
4      46039306           0.0
5      46039304           0.0
6      46039303           0.0
7      46039302           0.0
8      46039301           0.0
9      46038709           0.0
10     46038708           0.0
11     46038703           0.0
12     46038700           0.0
13     46038243           0.0
14     46038070           0.0
15     46038064           0.0
16     46038065           0.0
17     46038067           0.0
18     46038068           0.0
19     46038060           0.0
20     46038062           0.0
21     46038063           0.0
22     46038061           0.0
23     46037951           0.0
24     46037918           0.0
...         ...           ...
58155  45617123          37.0
58156  45616119          37.0
58157  45564943          42.0
58158  45521300          45.0
58159  45433480          51.0
58160  45383007          55.0
58161  45201485          74.0
58162  45168746          78.0
58163  45168743          78.0
58164  45168750          78.0
58165  45168752          78.0
58166  45168741          78.0
58167  44843897         112.0
58168  44789950         119.0
58169  44789940         119.0
58170  44682662         130.0
58171  44682652         130.0
58172  44658860         133.0
58173  44629286         137.0
58174  44629272         137.0
58175  44605893         140.0
58176  44457061         160.0
58177  42865848         358.0
58178  42734734         373.0
58179  42663515         382.0

[58180 rows x 2 columns]

### 11. Partition the dogs according to the number of weeks from the posted day to the day of last access.

In [292]:
dogs['numberOfWeeks'] = (dogs['numberOfDays'] / 7).round()
weekGroup = dogs.groupby(['numberOfWeeks'])
pd.DataFrame(weekGroup['id'].value_counts())

                        id
numberOfWeeks id
0.0           45938106   1
              45952908   1
              45978942   1
              45979050   1
              45979075   1
              45979879   1
              45984080   1
              45984097   1
              45985124   1
              45985135   1
              45985140   1
              45990290   1
              45990841   1
              46004482   1
              46004486   1
              46004490   1
              46004496   1
              46004497   1
              46004509   1
              46004516   1
              46004558   1
              46004571   1
              46004574   1
              46004576   1
              46004577   1
...                     ..
647.0         8327275    1
648.0         8270940    1
              8278699    1
649.0         8236865    1
654.0         8002933    1
658.0         7871495    1
659.0         7803760    1
660.0         7755992    1
662.0         7682837    1
664.0         7606897    1
669.0         7435741    1
671.0         7320934    1
              7320968    1
675.0         7184248    1
676.0         7125220    1
700.0         6129889    1
708.0         5859583    1
712.0         5741831    1
728.0         5201301    1
729.0         5178418    1
730.0         5142790    1
747.0         4527948    1
812.0         2613506    1
813.0         2592031    1
853.0         604115     1

[58147 rows x 1 columns]

### 12. Find for duplicates in the dogs dataset. Two records are duplicates if they have (1) same breeds and sex, and (2) they share at least 90% of the words in the description field. Extra points if you find and implement a more refined for determining if two rows are duplicates.

In [232]:
# Keeps all dogs with same breeds and sex
duplicatesDogs = dogs[['breed_primary', 'breed_secondary', 'breed_mixed', 'sex']].duplicated(keep=False)
duplicatesDogs = dogs[duplicatesDogs]
duplicatesDogs
#duplic3 = duplicatesDogs.duplicated(subset=['description'])
#duplicatesDogs[duplic3]

,id,org_id,url,type.x,species,breed_primary,breed_secondary,breed_mixed,breed_unknown,color_primary,color_secondary,color_tertiary,age,sex,size,coat,fixed,house_trained,declawed,special_needs,shots_current,env_children,env_dogs,env_cats,name,status,posted,contact_city,contact_state,contact_zip,contact_country,stateQ,accessed,type.y,description,stay_duration,stay_cost,sumTime
0,46042150,NV163,https://www.petfinder.com/dog/harley-46042150/...,Dog,Dog,American Staffordshire Terrier,Mixed Breed,True,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Senior,Male,Medium,Short,True,True,NaN,False,True,NaN,NaN,NaN,HARLEY,adoptable,NaT,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,Harley is not sure how he wound up at shelter ...,70,124.81,NaT
1,46042002,NV163,https://www.petfinder.com/dog/biggie-46042002/...,Dog,Dog,Pit Bull Terrier,Mixed Breed,True,False,Brown / Chocolate,White / Cream,NaN,Adult,Male,Large,Short,True,True,NaN,False,True,NaN,NaN,NaN,BIGGIE,adoptable,NaT,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,6 year old Biggie has lost his home and really...,49,122.07,NaT
2,46040898,NV99,https://www.petfinder.com/dog/ziggy-46040898/n...,Dog,Dog,Shepherd,NaN,False,False,Brindle,NaN,NaN,Adult,Male,Large,Short,True,False,NaN,False,True,NaN,NaN,NaN,Ziggy,adoptable,NaT,Mesquite,NV,89027,US,89009,2019-09-20,Dog,Approx 2 years old.\n Did I catch your eye? I ...,87,281.51,NaT
3,46039877,NV202,https://www.petfinder.com/dog/gypsy-46039877/n...,Dog,Dog,German Shepherd Dog,NaN,False,False,NaN,NaN,NaN,Baby,Female,Large,NaN,False,False,NaN,False,False,NaN,NaN,NaN,Gypsy,adoptable,NaT,Pahrump,NV,89048,US,89009,2019-09-20,Dog,NaN,62,145.83,NaT
4,46039306,NV184,https://www.petfinder.com/dog/theo-46039306/nv...,Dog,Dog,Dachshund,NaN,False,False,NaN,NaN,NaN,Young,Male,Small,Long,True,False,NaN,False,True,True,True,True,Theo,adoptable,NaT,Henderson,NV,89052,US,89009,2019-09-20,Dog,Theo is a friendly dachshund mix who gets alon...,93,241.09,NaT
5,46039304,NV184,https://www.petfinder.com/dog/oliver-46039304/...,Dog,Dog,Boxer,Beagle,True,False,NaN,NaN,NaN,Baby,Male,Medium,Short,True,False,NaN,False,True,True,True,True,Oliver,adoptable,NaT,Henderson,NV,89052,US,89009,2019-09-20,Dog,Oliver was born around mid-June and came to us...,70,97.77,NaT
6,46039303,NV184,https://www.petfinder.com/dog/macadamia-460393...,Dog,Dog,Italian Greyhound,Chihuahua,True,False,NaN,NaN,NaN,Baby,Female,Small,Short,True,False,NaN,False,True,True,True,True,Macadamia,adoptable,NaT,Henderson,NV,89052,US,89009,2019-09-20,Dog,Macadamia was born around July 8th and donât...,80,103.53,NaT
7,46039302,NV184,https://www.petfinder.com/dog/dodger-46039302/...,Dog,Dog,Cattle Dog,NaN,True,False,NaN,NaN,NaN,Baby,Male,Medium,Medium,True,False,NaN,False,True,True,True,True,Dodger,adoptable,NaT,Henderson,NV,89052,US,89009,2019-09-20,Dog,"Dodger is a handsome, smart Heeler mix who was...",46,79.91,NaT
8,46039301,NV184,https://www.petfinder.com/dog/huckleberry-4603...,Dog,Dog,Cattle Dog,NaN,True,False,NaN,NaN,NaN,Baby,Female,Medium,Medium,True,False,NaN,False,True,True,True,True,Huckleberry,adoptable,NaT,Henderson,NV,89052,US,89009,2019-09-20,Dog,Huckleberry is a friendly girl who was born Ma...,97,252.17,NaT
9,46038709,NV184,https://www.petfinder.com/dog/fagin-46038709/n...,Dog,Dog,Cattle Dog,NaN,True,False,NaN,NaN,NaN,Baby,Male,Medium,Medium,True,False,NaN,False,True,True,True,True,Fagin,adoptable,NaT,Henderson,NV,89052,US,89009,2019-09-20,Dog,"Fagin was born on May 26th and is a smart, inq...",112,137.19,NaT
10,46038708,NV184,https://www.petfinder.com/dog/speckles-4603870...,Dog,Dog,Cattle Dog,Hound,True,False,NaN,NaN,NaN,Baby,Female,Medium,Medium,True,False,NaN,False,True,True,True,True,Speckles,adoptable,NaT,Henderson,NV,89052,US,89009,2019-09-20,Dog,Speckles is a 4 month old Heeler/Hound mix who...,84,320.37,NaT
11,46038703,NV184,https://www.petfinder.com/dog/cashew-46038703/...,Dog,Dog,Italian Greyhound,Chihuahua,True,False,NaN,NaN,NaN,Baby,Female,Small,Short,True,False,NaN,False,True,True,True,True,Cashew,adoptable,NaT,Henderson,NV,89052,US,89009,2019-09-20,Dog,Cashew is sweet girl who was born around July ...,75,238.42,NaT
12,46038700,NV184,https://www.petfinder.com/dog/dash-46038700/nv...,Dog,Dog,Cattle Dog,NaN,True,False,NaN,NaN,NaN,Baby,Male,Medium,Medium,True,False,NaN,False,True,True,True,NaN,Dash,adoptable,NaT,Henderson,NV,89052,US,89009,2019-09-20,Dog,"Born May 26th, Dash is a handsome, spirited bo...",78,76.87,NaT
13,46038243,NV155,https://www.petfinder.com/dog/sydney-46038243/...,Dog,Dog,Border Collie,NaN,True,False,Black,White / Cream,NaN,Adult,Female,Medium,Short,True,True,NaN,False,True,NaN,True,NaN,Sydney,adoptable,NaT,Las Vegas,NV,89103,US,89009,2019-09-20,Dog,Meet Sydney- Sheâs a 5 year old Border Colli...,115,130.30,NaT
14,46038070,NV26,https://www.petfinder.com/dog/henna-46038070/n...,Dog,Dog,Pit Bull Terrier,NaN,True,False,NaN,NaN,NaN,Young,Female,Large,NaN,True,False,NaN,False,False,NaN,NaN,NaN,HENNA,adoptable,NaT,Las Vegas,NV,89101,US,89009,2019-09-20,Dog,NaN,117,544.07,NaT
15,46038064,NV26,https://www.petfinder.com/dog/rubo-46038064/nv...,Dog,Dog,German Shepherd Dog,NaN,True,False,NaN,NaN,NaN,Adult,Male,Extra Large,NaN,True,False,NaN,False,False,NaN,NaN,NaN,RUBO,adoptable,NaT,Las Vegas,NV,89101,US,89009,2019-09-20,Dog,NaN,114,300.71,NaT
16,46038065,NV26,https://www.petfinder.com/dog/lego-46038065/nv...,Dog,Dog,Schnauzer,Mixed Breed,True,False,NaN,NaN,NaN,Adult,Male,Medium,NaN,True,False,NaN,False,False,NaN,NaN,NaN,LEGO,adoptable,NaT,Las Vegas,NV,89101,US,89009,2019-09-20,Dog,NaN,82,285.86,NaT
17,46038067,NV26,https://www.petfinder.com/dog/marie-46038067/n...,Dog,Dog,Pit Bull Terrier,NaN,True,False,NaN,NaN,NaN,Adult,Female,Large,NaN,True,False,NaN,False,False,NaN,NaN,NaN,MARIE,adoptable,NaT,Las Vegas,NV,89101,US,89009,2019-09-20,Dog,NaN,136,231.52,NaT
18,46038068,NV26,https://www.petfinder.com/dog/ringo-46038068/n...,Dog,Dog,Boxer,NaN,True,False,NaN,NaN,NaN,Young,Male,Large,NaN,True,False,NaN,False,False,NaN,NaN,NaN,RINGO,adoptable,NaT,Las Vegas,NV,89101,US,89009,2019-09-20,Dog,NaN,94,361.96,NaT
19,46038060,NV26,https://www.petfinder.com/dog/tony-46038060/nv...,Dog,Dog,Pit Bull Terrier,NaN,True,False,NaN,NaN,NaN,Young,Male,Medium,NaN,True,False,NaN,False,False,NaN,NaN,NaN,TONY,adoptable,NaT,Las Vegas,NV,89101,US,89009,2019-09-20,Dog,NaN,91,197.93,NaT
20,46038062,NV26,https://www.petfinder.com/dog/duncan-46038062/...,Dog,Dog,Pit Bull Terrier,NaN,True,False,NaN,NaN,NaN,Young,Male,Large,NaN,True,False,NaN,False,False,NaN,NaN,NaN,DUNCAN,adoptable,NaT,Las Vegas,NV,89101,US,89009,2019-09-20,Dog,NaN,80,91.22,NaT
21,46038063,NV26,https://www.petfinder.com/dog/o-and-number-39c...,Dog,Dog,Pit Bull Terrier,NaN,True,False,NaN,NaN,NaN,Adult,Male,Large,NaN,True,False,NaN,False,False,NaN,NaN,NaN,O&#39;CONNOR,adoptable,NaT,Las Vegas,NV,89101,US,89009,2019-09-20,Dog,NaN,88,353.15,NaT
22,46038061,NV26,https://www.petfinder.com/dog/cream-46038061/n...,Dog,Dog,Dachshund,Mixed Breed,True,False,NaN,NaN,NaN,Baby,Male,Small,NaN,False,False,NaN,False,False,NaN,NaN,NaN,CREAM,adoptable,NaT,Las Vegas,NV,89101,US,89009,2019-09-20,Dog,NaN,119,486.27,NaT
23,46037951,NV155,https://www.petfinder.com/dog/kimberly-aka-fre...,Dog,Dog,Shepherd,Border Collie,True,False,"Tricolor (Brown, Black, & White)",NaN,NaN,Baby,Female,Medium,Short,True,True,NaN,False,True,NaN,True,NaN,Kimberly aka Freckles,adoptable,NaT,Las Vegas,NV,89103,US,89009,2019-09-20,Dog,Hello my name is Kimberly âFrecklesâ! I wa...,75,154.77,NaT
25,46037881,NV187,https://www.petfinder.com/dog/max-46037881/nv/...,Dog,Dog,Cocker Spaniel,Beagle,True,False,NaN,NaN,NaN,Senior,Male,Medium,NaN,True,False,NaN,True,False,True,True,True,Max,adoptable,NaT,Las Vegas,NV,89103,US,89009,2019-09-20,Dog,Max came to our rescue from a young man who ha...,90,263.93,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58154,45655714,WY24,https://www.petfinder.com/dog/loki-45655714/wy...,Dog,Dog,Shepherd,Mixed Breed,True,False,NaN,NaN,NaN,Young,Male,Medium,NaN,True,True,NaN,False,False,True,True,False,Loki,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,"Loki was one of our frequent flyers, meaning h...",103,286.90,NaT
58155,45617123,WY24,https://www.petfinder.com/dog/malachi-45617123...,Dog,Dog,Border Collie,Mixed Breed,True,False,NaN,NaN,NaN,Young,Male,Medium,NaN,True,False,NaN,False,False,True,True,True,Malachi,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,"When our Sheriff's Dept brought Malachi in, th...",120,458.46,NaT
58156,45616119,WY24,https://www.petfinder.com/dog/alex-45616119/wy...,Dog,Dog,Labrador Retriever,Mixed Breed,True,False,NaN,NaN,NaN,Young,Male,Medium,NaN,True,False,NaN,True,False,True,True,True,Alex,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,Alex came to us as a stray through our Police ...,78,248.69,NaT
58157,45564943,WY04,https://www.petfinder.com/dog/lulu-45564943/wy...,Dog,Dog,Labrador Retriever,Pit Bull Terrier,True,False,Black,White / Cream,NaN,Adult,Female,Medium,Short,True,False,NaN,False,True,False,False,False,Lulu,adoptable,NaT,Worland,WY,82401,US,WY,2019-09-20,Dog,NaN,57,178.85,NaT
58158,45521300,WY04,https://www.petfinder.com/dog/ranger-45521300/...,Dog,Dog,Labrador Retriever,Collie,True,False,Black,White / Cream,NaN,Adult,Male,Medium,Short,True,False,NaN,False,True,NaN,False,False,Ranger,adoptable,NaT,Worland,WY,82401,US,WY,2019-09-20,Dog,NaN,89,444.78,NaT
58159,45433480,WY11,https://www.petfinder.com/dog/la-rooh-45433480...,Dog,Dog,Pit Bull Terrier,Mixed Breed,True,False,NaN,NaN,NaN,Adult,Female,Medium,NaN,True,False,NaN,False,False,NaN,NaN,NaN,LA-ROOH,adoptable,NaT,Casper,WY,82601,US,WY,2019-09-20,Dog,NaN,74,123.51,NaT
58160,45383007,WY24,https://www.petfinder.com/dog/baby-girl-453830...,Dog,Dog,American Staffordshire Terrier,Mixed Breed,True,False,NaN,NaN,NaN,Adult,Female,Large,NaN,True,False,NaN,False,False,False,False,True,Baby Girl,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,Our Baby Girl has had a rough life: bred every...,74,190.52,NaT
58161,45201485,WY04,https://www.petfinder.com/dog/butch-45201485/w...,Dog,Dog,Border Collie,Australian Cattle Dog / Blue Heeler,True,False,Black,White / Cream,NaN,Adult,Male,Medium,Short,True,False,NaN,False,True,True,True,NaN,Butch,adoptable,NaT,Worland,WY,82401,US,WY,2019-09-20,Dog,NaN,91,277.14,NaT
58162,45168746,WY24,https://www.petfinder.com/dog/buddy-45168746/w...,Dog,Dog,Terrier,Mixed Breed,True,False,NaN,NaN,NaN,Adult,Male,Large,NaN,True,False,NaN,False,False,True,True,True,Buddy,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,Buddy is another staff favorite because of his...,109,203.95,NaT
58163,45168743,WY24,https://www.petfinder.com/dog/sammy-45168743/w...,Dog,Dog,Labrador Retriever,Mixed Breed,True,False,NaN,NaN,NaN,Young,Male,Large,NaN,True,False,NaN,False,False,True,True,True,Sammy,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,Sammy is one happy puppy that we literally had...,115,290.28,NaT
58164,45168750,WY24,https://www.petfinder.com/dog/dwayne-45168750/...,Dog,Dog,Australian Cattle Dog / Blue Heeler,Mixed Breed,True,False,NaN,NaN,NaN,Young,Male,Medium,NaN,True,False,NaN,False,False,True,True,True,Dwayne,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,"Dwayne is your typical adolescent: happy, play...",110,254.27,NaT
58165,45168752,WY24,https://www.petfinder.com/dog/sebastian-451687...,Dog,Dog,Australian Shepherd,Border Collie,True,False,NaN,NaN,NaN,Young,Male,Medium,NaN,True,False,NaN,False,False,True,True,True,Sebastian,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,Sebastian is your typical herding dog: high en...,105,171.81,NaT
58166,45168741,WY24,https://www.petfinder.com/dog/charlie-45168741...,Dog,Dog,Australian Shepherd,Australian Cattle Dog / Blue Heeler,True,False,NaN,NaN,NaN,Adult,Male,Medium,NaN,True,False,NaN,False,False,True,True,True,Charlie,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,"Charlie was adopted from us 5 years ago, but r...",109,280.51,NaT
58167,44843897,WY24,https://www.petfinder.com/dog/samson-44843897/...,Dog,Dog,Pit Bull Terrier,NaN,False,False,NaN,NaN,NaN,Adult,Male,Large,NaN,True,False,NaN,False,False,True,True,True,Samson,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,Samson is a dog that will need someone to show...,74,132.32,NaT
58168,44789950,WY04,https://www.petfinder.com/dog/mandie-44789950/...,Dog,Dog,Black Labrador Retriever,Shar-Pei,True,False,Black,White / Cream,NaN,Adult,Female,Medium,Short,True,False,NaN,False,True,True,True,True,Mandie,adoptable,NaT,Worland,WY,82401,US,WY,2019-09-20,Dog,NaN,93,239.75,NaT
58170,44682662,WY04,https://www.petfinder.com/dog/sam-44682662/wy/...,Dog,Dog,Labrador Retriever,Pit Bull Terrier,True,False,Black,Yellow / Tan / Blond / Fawn,NaN,Adult,Male,Medium,Short,True,False,NaN,False,True,True,True,False,Sam,adoptable,NaT,Worland,WY,82401,US,WY,2019-09-20,Dog,NaN,90,250.20,NaT
58171,44682652,WY04,https://www.petfinder.com/dog/apollo-44682652/...,Dog,Dog,Labrador Retriever,Shar-Pei,True,False,Golden,NaN,NaN,Adult,Male,Medium,Short,True,False,NaN,False,True,True,False,False,Apollo,adoptable,NaT,Worland,WY,82401,US,WY,2019-09-20,Dog,NaN,91,237.33,NaT
58172,44658860,WY24,https://www.petfinder.com/dog/buddy-44658860/w...,Dog,Dog,Pit Bull Terrier,Mixed Breed,True,False,NaN,NaN,NaN,Baby,Male,Medium,NaN,True,True,NaN,False,False,True,True,True,Buddy,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,Buddy was an owner surrender by an older gentl...,135,357.97,NaT
58173,44629286,WY04,https://www.petfinder.com/dog/suzi-44629286/wy...,Dog,Dog,Labrador Retriever,Hound,True,False,Brown / Chocolate,White / Cream,NaN,Adult,Female,Medium,Short,True,False,NaN,False,True,False,False,False,Suzi,adoptable,NaT,Worland,WY,82401,US,WY,2019-09-20,Dog,NaN,61,167.10,NaT
58174,44629272,WY04,https://www.petfinder.com/dog/cheyenne-4462927...,Dog,Dog,Shepherd,Australian Cattle Dog / Blue Heeler,True,False,Brown / Chocolate,NaN,NaN,Young,Female,Medium,Short,True,False,NaN,False,True,True,True,NaN,Cheyenne,adoptable,NaT,Worland,WY,82401,US,WY,2019-09-20,Dog,NaN,97,242.85,NaT
58175,44605893,WY20,https://www.petfinder.com/dog/tren-44605893/wy...,Dog,Dog,Border Collie,NaN,False,False,"Tricolor (Brown, Black, & White)",NaN,NaN,Adult,Male,Medium,Medium,True,True,NaN,False,False,NaN,NaN,NaN,Tren,adoptable,NaT,Lander,WY,82520,US,WY,2019-09-20,Dog,"Due to the small size of our volunteer base, w...",100,324.34,NaT
58176,44457061,WY24,https://www.petfinder.com/dog/harley-44457061/...,Dog,Dog,Australian Shepherd,Australian Cattle Dog / Blue Heeler,True,False,NaN,NaN,NaN,Young,Female,Medium,NaN,True,False,NaN,False,False,False,False,False,Harley,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,65,245.90,NaT
58177,42865848,WY20,https://www.petfinder.com/dog/echo-42865848/wy...,Dog,Dog,Border Collie,NaN,False,False,NaN,NaN,NaN,Adult,Female,Medium,Medium,True,True,NaN,False,True,NaN,NaN,NaN,Echo,adoptable,NaT,Glenrock,WY,82637,US,WY,2019-09-20,Dog,"Due to the small size of our volunteer base, w...",100,184.06,NaT
58178,42734734,WY24,https://www.petfinder.com/dog/simon-42734734/w...,Dog,Dog,Boxer,Mixed Breed,True,False,NaN,NaN,NaN,Senior,Male,Large,NaN,True,False,NaN,False,False,True,True,True,Simon,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,58,61.05,NaT
58179,42663515,WY24,https://www.petfinder.com/dog/romeo-42663515/w...,Dog,Dog,Labrador Retriever,Pit Bull Terrier,True,False,NaN,NaN,NaN,Adult,Male,Large,NaN,True,False,NaN,False,False,True,True,True,Romeo,adoptable,NaT,Riverton,WY,82501,US,WY,2019-09-20,Dog,NaN,100,255.38,NaT